import 'package:flutter/material.dart';
import 'package:flutterapp/view/lightsapp/logupScreen1/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/view/lightsapp/logupScreen1/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/view/lightsapp/logupScreen1/generated/GeneratedEmailWidget1.dart';
import 'package:flutterapp/view/lightsapp/logupScreen1/generated/GeneratedVectorWidget5.dart';
import 'package:flutterapp/view/lightsapp/logupScreen1/generated/GeneratedHocviWidget1.dart';
import 'package:flutterapp/view/lightsapp/logupScreen1/generated/GeneratedNGKWidget.dart';
import 'package:flutterapp/view/lightsapp/logupScreen1/generated/GeneratedAddressWidget.dart';
import 'package:flutterapp/view/lightsapp/logupScreen1/generated/GeneratedPhoneNumberWidget.dart';
import 'package:flutterapp/view/lightsapp/logupScreen1/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/view/lightsapp/logupScreen1/generated/Generated810Widget1.dart';

/* Frame logup screen 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogupscreen1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/e283b33ab7375327428a58bc4d7aa0f81936911c.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 360.0,
                  height: 800.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 55.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 273.0,
                height: 450.0,
                child: Generated810Widget1(),
              ),
              Positioned(
                left: 93.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 55.0,
                child: GeneratedNGKWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.09166666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 33.0;

                  double percentHeight = 0.04125;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 33.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.044444444444444446,
                        translateY: constraints.maxHeight * 0.02375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget5())
                  ]);
                }),
              ),
              Positioned(
                left: 7.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 60.0,
                child: GeneratedGroup11Widget(),
              ),
              Positioned(
                left: 128.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 36.0,
                child: GeneratedHocviWidget1(),
              ),
              Positioned(
                left: 18.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 71.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 75.0,
                child: GeneratedNameWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 442.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 75.0,
                child: GeneratedEmailWidget1(),
              ),
              Positioned(
                left: 18.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 320.0000305175781,
                height: 75.0,
                child: GeneratedPhoneNumberWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 75.0,
                child: GeneratedAddressWidget(),
              )
            ]),
      ),
    ));
  }
}
