import 'package:flutter/material.dart';
import 'package:flutterapp/view/lightsapp/generatedloginscreenwidget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/view/lightsapp/generatedloginscreenwidget/generated/GeneratedQunWidget.dart';
import 'package:flutterapp/view/lightsapp/generatedloginscreenwidget/generated/GeneratedLogupWidget.dart';
import 'package:flutterapp/view/lightsapp/generatedloginscreenwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/view/lightsapp/generatedloginscreenwidget/generated/GeneratedGoogleWidget.dart';
import 'package:flutterapp/view/lightsapp/generatedloginscreenwidget/generated/GeneratedTwitterWidget.dart';
import 'package:flutterapp/view/lightsapp/generatedloginscreenwidget/generated/Generated810Widget.dart';
import 'package:flutterapp/view/lightsapp/generatedloginscreenwidget/generated/GeneratedInstaWidget.dart';
import 'package:flutterapp/view/lightsapp/generatedloginscreenwidget/generated/GeneratedHocviWidget.dart';
import 'package:flutterapp/view/lightsapp/generatedloginscreenwidget/generated/GeneratedLoginWidget.dart';
import 'package:flutterapp/view/lightsapp/generatedloginscreenwidget/generated/GeneratedNGNHPWidget.dart';
import 'package:flutterapp/view/lightsapp/generatedloginscreenwidget/generated/GeneratedFacebookWidget.dart';

/* Frame login screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/e283b33ab7375327428a58bc4d7aa0f81936911c.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 360.0,
                  height: 800.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 55.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 273.0,
                height: 450.0,
                child: Generated810Widget(),
              ),
              Positioned(
                left: 66.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 55.0,
                child: GeneratedNGNHPWidget(),
              ),
              Positioned(
                left: 102.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedInstaWidget(),
              ),
              Positioned(
                left: 197.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedTwitterWidget(),
              ),
              Positioned(
                left: 292.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedGoogleWidget(),
              ),
              Positioned(
                left: 7.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedFacebookWidget(),
              ),
              Positioned(
                left: 128.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 36.0,
                child: GeneratedHocviWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 407.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 71.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 545.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 71.0,
                child: GeneratedLoginWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 639.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 71.0,
                child: GeneratedLogupWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 313.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 71.0,
                child: GeneratedEmailWidget(),
              ),
              Positioned(
                left: 274.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 33.0,
                child: GeneratedQunWidget(),
              )
            ]),
      ),
    ));
  }
}
