description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^1.0.5"
  path_drawing: "^1.0.0"
  rive:
  shared_preferences: ^2.2.0
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.17.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
    - "assets/rive/"
    - "assets/rive/star.riv"
  fonts: 
    - 
      family: "Paytone One"
      fonts: 
        - 
          asset: "fonts/PaytoneOne-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Mistrully"
      fonts: 
        - 
          asset: "fonts/Mistrully.ttf"
          style: "normal"
          weight: 400
    - family: "MyFlutterApp"
      fonts:
        - asset: "fonts/MyFlutterApp.ttf"
  uses-material-design: true
