description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies:
  provider: ^6.0.5
  mobile_scanner: ^3.5.1
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.14
  velocity_x: ^3.6.0
  carousel_slider: ^4.2.1
  cupertino_icons: "^1.0.5"
  path_drawing: "^1.0.0"
  rive:
  shared_preferences:
  yaml:
  visibility_detector:
  chat_bubbles:
  flutter_svg:
  flutter_gif:
  custom_clippers:
  fl_chart: ^0.63.0
  flutter_social_button:
  table_calendar:
  fluentui_emoji_icon:
  video_player: 2.7.2
  circle_list:
  intl:
  image_picker:
  flutter_keyboard_visibility:
  flutter:
    sdk: "flutter"
  http: ^0.13.5
  socket_io_client: ^2.0.3+1
  get: ^4.6.5
  just_audio: ^0.9.28
  rxdart: ^0.27.5
  qr_flutter: ^4.1.0
  qr_scanner_overlay: ^0.0.2
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 16 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
environment:
  sdk: ">3.0.0"
flutter:
  assets:
    - "assets/images/"
    - "assets/rive/"
    - "assets/config.yml"
    - "assets/images/movie/"
    - "assets/images/music/"
    - "assets/images/game/"
    - "assets/images/ava/"
    - "fonts/DFVNBoris.otf"
  fonts:
    - family: "Paytone One"
      fonts:
        - asset: "fonts/PaytoneOne-regular.ttf"
          style: "normal"
          weight: 400
    - family: "DancingScript"
      fonts:
        - asset: "fonts/DancingScript.ttf"
          style: "normal"
          weight: 400
    - family: "Mistrully"
      fonts:
        - asset: "fonts/Mistrully.ttf"
          style: "normal"
          weight: 400
    - family: "SuperComic"
      fonts:
        - asset: "fonts/SuperComic.ttf"
          style: "normal"
          weight: 400
    - family: "DFVNDoris"
      fonts:
        - asset: "fonts/DFVNBoris.otf"
          style: "normal"
          weight: 400
    - family: "MyFlutterApp"
      fonts:
        - asset: "fonts/MyFlutterApp.ttf"
    - family: "PinnacleJYLiningBookItalic"
      fonts:
        - asset: "fonts/PinnacleJYLiningBookItalic.ttf"
          style: "normal"
          weight: 400
  uses-material-design: true