description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies:
  chat_gpt_sdk: ^2.2.4
  fluttertoast: ^8.2.2
  video_player: ^2.7.2
  url_launcher: ^6.1.14
  chewie: ^1.7.1
  velocity_x: ^3.6.0
  carousel_slider: ^4.2.1
  cupertino_icons: "^1.0.5"
  path_drawing: "^1.0.0"
  rive:
  shared_preferences:
  yaml:
  visibility_detector:
  flutter_custom_clippers: ^2.1.0
  custom_clippers: ^2.0.0
  chat_bubbles:
  flutter_svg:
  flutter_gif:
  fl_chart: ^0.63.0
  flutter:
    sdk: "flutter"
  http: ^0.13.5
  socket_io_client: ^2.0.3+1
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 16 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
environment:
  sdk: ">3.0.0"
flutter: 
  assets:
    - "assets/images/"
    - "assets/rive/"
    - "assets/config.yml"
    - "assets/images/movie/"
  fonts: 
    - 
      family: "Paytone One"
      fonts: 
        - 
          asset: "fonts/PaytoneOne-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Mistrully"
      fonts: 
        - 
          asset: "fonts/Mistrully.ttf"
          style: "normal"
          weight: 400
    - family: "MyFlutterApp"
      fonts:
        - asset: "fonts/MyFlutterApp.ttf"
  uses-material-design: true