import 'package:flutter/material.dart';
import 'package:flutterapp/lightsapp/generatedloginscreenwidget/generated/GeneratedNGNHPWidget.dart';
import 'package:flutterapp/lightsapp/generatedloginscreenwidget/generated/GeneratedFacebookWidget.dart';
import 'package:flutterapp/lightsapp/generatedloginscreenwidget/generated/GeneratedVectorWidget.dart';
import 'package:flutterapp/lightsapp/generatedloginscreenwidget/generated/GeneratedTwitterWidget.dart';
import 'package:flutterapp/lightsapp/generatedloginscreenwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lightsapp/generatedloginscreenwidget/generated/GeneratedGoogleWidget.dart';
import 'package:flutterapp/lightsapp/generatedloginscreenwidget/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/lightsapp/generatedloginscreenwidget/generated/GeneratedInstaWidget.dart';
import 'package:flutterapp/lightsapp/generatedloginscreenwidget/generated/GeneratedQunWidget.dart';
import 'package:flutterapp/lightsapp/generatedloginscreenwidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/lightsapp/generatedloginscreenwidget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/lightsapp/generatedloginscreenwidget/generated/Generated810Widget.dart';
import 'package:flutterapp/lightsapp/generatedloginscreenwidget/generated/GeneratedHocviWidget.dart';

/* Frame login screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            ////overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/3890c3231620d942b721643b360ba38e7aa00362.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 360.0,
                  height: 800.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 55.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 273.0,
                height: 450.0,
                child: Generated810Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: GeneratedRectangle1Widget2(),
              ),
              Positioned(
                left: 66.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 55.0,
                child: GeneratedNGNHPWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.1111111111111111;
                  double scaleX = (constraints.maxWidth * percentWidth) / 40.0;

                  double percentHeight = 0.05;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 40.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.044444444444444446,
                        translateY: constraints.maxHeight * 0.02375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget())
                  ]);
                }),
              ),
              Positioned(
                left: 102.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedInstaWidget(),
              ),
              Positioned(
                left: 197.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedTwitterWidget(),
              ),
              Positioned(
                left: 292.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedGoogleWidget(),
              ),
              Positioned(
                left: 7.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedFacebookWidget(),
              ),
              Positioned(
                left: 128.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 36.0,
                child: GeneratedHocviWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 407.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 71.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 71.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 313.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 71.0,
                child: GeneratedEmailWidget(),
              ),
              Positioned(
                left: 274.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 33.0,
                child: GeneratedQunWidget(),
              )
            ]),
      ),
    ));
  }
}
