import 'package:flutter/material.dart';
import 'package:flutterapp/lightsapp/generatedmainscreenwidget/generated/GeneratedMissionWidget.dart';
import 'package:flutterapp/lightsapp/generatedmainscreenwidget/generated/GeneratedHeaderWidget.dart';
import 'package:flutterapp/lightsapp/generatedmainscreenwidget/generated/GeneratedSettingWidget.dart';
import 'package:flutterapp/lightsapp/generatedmainscreenwidget/generated/GeneratedHomeWidget.dart';
import 'package:flutterapp/lightsapp/generatedmainscreenwidget/generated/Generated811Widget.dart';
import 'package:flutterapp/lightsapp/generatedmainscreenwidget/generated/GeneratedNotiWidget.dart';

/* Frame mainScreen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMainScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/85467c0186aa1e39f7aba60db02bf4fe6c044214.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 360.0,
                  height: 800.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 55.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 242.9104461669922,
                height: 450.0,
                child: Generated811Widget(),
              ),
              Positioned(
                left: 118.0,
                top: 719.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 57.0,
                child: GeneratedHomeWidget(),
              ),
              Positioned(
                left: 199.0,
                top: 719.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 57.0,
                child: GeneratedNotiWidget(),
              ),
              Positioned(
                left: 280.0,
                top: 719.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 57.0,
                child: GeneratedMissionWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 52.0,
                child: GeneratedHeaderWidget(),
              ),
              Positioned(
                left: 11.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 38.0,
                child: GeneratedSettingWidget(),
              )
            ]),
      ),
    ));
  }
}
