import 'package:flutter/material.dart';
import 'package:flutterapp/lightsapp/generatedforgotpasswordscreen2widget/generated/GeneratedVectorWidget7.dart';
import 'package:flutterapp/lightsapp/generatedforgotpasswordscreen2widget/generated/Generated810Widget2.dart';
import 'package:flutterapp/lightsapp/generatedforgotpasswordscreen2widget/generated/GeneratedRectangle1Widget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lightsapp/generatedforgotpasswordscreen2widget/generated/GeneratedChngtisgimOTPnsinthoicabnWidget.dart';
import 'package:flutterapp/lightsapp/generatedforgotpasswordscreen2widget/generated/GeneratedBNQUNMTKHUWidget1.dart';
import 'package:flutterapp/lightsapp/generatedforgotpasswordscreen2widget/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/lightsapp/generatedforgotpasswordscreen2widget/generated/GeneratedNhpmOTPWidget.dart';
import 'package:flutterapp/lightsapp/generatedforgotpasswordscreen2widget/generated/GeneratedGroup5Widget1.dart';

/* Frame forgot password screen 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedForgotpasswordscreen2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            ////overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/3890c3231620d942b721643b360ba38e7aa00362.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 360.0,
                  height: 800.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 55.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 273.0,
                height: 450.0,
                child: Generated810Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: GeneratedRectangle1Widget4(),
              ),
              Positioned(
                left: 70.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 223.0,
                height: 113.0,
                child: GeneratedBNQUNMTKHUWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.1111111111111111;
                  double scaleX = (constraints.maxWidth * percentWidth) / 40.0;

                  double percentHeight = 0.05;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 40.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.044444444444444446,
                        translateY: constraints.maxHeight * 0.02375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget7())
                  ]);
                }),
              ),
              Positioned(
                left: 16.0,
                top: 442.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 71.0,
                child: GeneratedGroup5Widget1(),
              ),
              Positioned(
                left: 17.0,
                top: 313.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 71.0,
                child: GeneratedRectangle3Widget2(),
              ),
              Positioned(
                left: 112.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 30.0,
                child: GeneratedNhpmOTPWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 198.0,
                right: null,
                bottom: null,
                width: 289.0,
                height: 63.0,
                child: GeneratedChngtisgimOTPnsinthoicabnWidget(),
              )
            ]),
      ),
    ));
  }
}
