import 'package:flutter/material.dart';

/* Text Quên
    Autogenerated by FlutLab FTF Generator
  */
class Text_Quen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () =>
          // Navigator.pushNamed(context, '/GeneratedForgotpasswordscreen1Widget'),          Navigator.pushNamed(context, '/GeneratedForgotpasswordscreen1Widget'),
          Navigator.pushNamed(context, '/Story'),
      child: Text(
        '''Quên mật khẩu''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 1.3960000038146974,
          fontSize: 20.0,
          fontFamily: 'Paytone One',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 69, 70, 70),

          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
