import 'package:flutter/material.dart';
import 'package:flutterapp/view/lightsapp/generatedlogupscreen2widget/generated/GeneratedBODWidget.dart';
import 'package:flutterapp/view/lightsapp/generatedlogupscreen2widget/generated/GeneratedRepassWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/view/lightsapp/generatedlogupscreen2widget/generated/GeneratedGroup4Widget1.dart';
import 'package:flutterapp/view/lightsapp/generatedlogupscreen2widget/generated/GeneratedPassWidget.dart';
import 'package:flutterapp/view/lightsapp/generatedlogupscreen2widget/generated/Generated810Widget2.dart';
import 'package:flutterapp/view/lightsapp/generatedlogupscreen2widget/generated/GeneratedHocviWidget2.dart';
import 'package:flutterapp/view/lightsapp/generatedlogupscreen2widget/generated/GeneratedGroup11Widget1.dart';
import 'package:flutterapp/view/lightsapp/generatedlogupscreen2widget/generated/GeneratedNGKWidget1.dart';
import 'package:flutterapp/view/lightsapp/generatedlogupscreen2widget/generated/GeneratedVectorWidget10.dart';

/* Frame logup screen 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogupscreen2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/e283b33ab7375327428a58bc4d7aa0f81936911c.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 360.0,
                  height: 800.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 55.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 273.0,
                height: 450.0,
                child: Generated810Widget2(),
              ),
              Positioned(
                left: 93.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 55.0,
                child: GeneratedNGKWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.09166666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 33.0;

                  double percentHeight = 0.04125;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 33.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.044444444444444446,
                        translateY: constraints.maxHeight * 0.02375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget10())
                  ]);
                }),
              ),
              Positioned(
                left: 7.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 60.0,
                child: GeneratedGroup11Widget1(),
              ),
              Positioned(
                left: 128.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 36.0,
                child: GeneratedHocviWidget2(),
              ),
              Positioned(
                left: 18.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 71.0,
                child: GeneratedGroup4Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 75.0,
                child: GeneratedBODWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 75.0,
                child: GeneratedPassWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 317.7622375488281,
                height: 75.0,
                child: GeneratedRepassWidget(),
              )
            ]),
      ),
    ));
  }
}
