import 'package:flutter/material.dart';
import 'package:flutterapp/lightsapp/generatedstoryscreen1widget/generated/Generated87Widget.dart';
import 'package:flutterapp/lightsapp/generatedstoryscreen1widget/generated/GeneratedHycngLightsTonnnhngiukdiunhWidget.dart';

/* Frame story screen 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStoryscreen1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedMainScreenWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 800.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              //overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Image.asset(
                    "assets/images/3890c3231620d942b721643b360ba38e7aa00362.png",
                    color: null,
                    fit: BoxFit.cover,
                    width: 360.0,
                    height: 800.0,
                    colorBlendMode: BlendMode.dstATop,
                  ),
                ),
                Positioned(
                  left: 7.0,
                  top: 55.0,
                  right: null,
                  bottom: null,
                  width: 348.0,
                  height: 77.0,
                  child: GeneratedHycngLightsTonnnhngiukdiunhWidget(),
                ),
                Positioned(
                  left: 55.0,
                  top: 253.0,
                  right: null,
                  bottom: null,
                  width: 273.0,
                  height: 450.0,
                  child: Generated87Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
