import 'package:flutter/material.dart';
import 'package:flutterapp/lightsapp/generatedstoryscreen1widget/generated/GeneratedHycngLightsTonnnhngiukdiunhWidget.dart';
import 'package:flutterapp/lightsapp/generatedstoryscreen1widget/generated/Generated84Widget.dart';

/* Frame story screen 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStoryscreen1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            // overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/3890c3231620d942b721643b360ba38e7aa00362.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 360.0,
                  height: 800.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 7.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 77.0,
                child: GeneratedHycngLightsTonnnhngiukdiunhWidget(),
              ),
              Positioned(
                left: -42.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 430.0,
                height: 776.0,
                child: Generated84Widget(),
              )
            ]),
      ),
    ));
  }
}
