import 'package:flutter/material.dart';
import 'package:flutterapp/lightsapp/generatedafterstoryscreenwidget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/lightsapp/generatedafterstoryscreenwidget/generated/Generated88Widget.dart';
import 'package:flutterapp/lightsapp/generatedafterstoryscreenwidget/generated/GeneratedGroup1Widget.dart';

/* Frame after story screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAfterstoryscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/cfeabdfbed2717f02dab508e472955062aca37cc.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 360.0,
                  height: 800.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 55.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 273.0,
                height: 450.0,
                child: Generated88Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 127.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 127.0,
                child: GeneratedGroup1Widget(),
              )
            ]),
      ),
    ));
  }
}
