import 'package:flutter/material.dart';
import 'package:flutterapp/util/rive/RiveUtil.dart';
import 'package:rive/rive.dart';

/* Rectangle 8 10
    Autogenerated by FlutLab FTF Generator
  */
class Whale extends StatefulWidget {

  @override
  State<StatefulWidget> createState() => WhaleState();
}

class WhaleState extends State<Whale> {
  RiveUtil? riveUtil;

  @override
  Widget build(BuildContext context) {
    Widget child;
    try {
      child = RiveAnimation.direct(
          riveUtil!.WHALE,
          fit: BoxFit.fill
      );
    } catch (e) {
      child = Container();
    }
    return Container(
      width: 273.0,
      height: 450.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: child
      ),
    );
  }

  @override
  void initState() {
    riveUtil = RiveUtil();
  }

}
