import 'package:flutter/material.dart';
import 'package:flutterapp/view/lightsapp/generatedforgotpasswordscreen3widget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/view/lightsapp/generatedforgotpasswordscreen3widget/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/view/lightsapp/generatedforgotpasswordscreen3widget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/view/lightsapp/generatedforgotpasswordscreen3widget/generated/GeneratedBNQUNMTKHUWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/view/lightsapp/generatedforgotpasswordscreen3widget/generated/GeneratedNhpmtkhumicabnnhWidget.dart';
import 'package:flutterapp/view/lightsapp/generatedforgotpasswordscreen3widget/generated/GeneratedVectorWidget18.dart';
import 'package:flutterapp/view/lightsapp/generatedforgotpasswordscreen3widget/generated/Generated810Widget6.dart';

/* Frame forgot password screen 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedForgotpasswordscreen3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/e283b33ab7375327428a58bc4d7aa0f81936911c.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 360.0,
                  height: 800.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 55.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 273.0,
                height: 450.0,
                child: Generated810Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.09166666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 33.0;

                  double percentHeight = 0.04125;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 33.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.044444444444444446,
                        translateY: constraints.maxHeight * 0.02375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget18())
                  ]);
                }),
              ),
              Positioned(
                left: 70.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 223.0,
                height: 113.0,
                child: GeneratedBNQUNMTKHUWidget2(),
              ),
              Positioned(
                left: 18.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 71.0,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 313.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 71.0,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 71.0,
                child: GeneratedGroup8Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 198.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 30.0,
                child: GeneratedNhpmtkhumicabnnhWidget(),
              )
            ]),
      ),
    ));
  }
}
