import 'package:flutter/material.dart';
import 'package:flutterapp/lightsapp/generatedfavoritescreenwidget/generated/GeneratedGroup4Widget3.dart';
import 'package:flutterapp/lightsapp/generatedfavoritescreenwidget/generated/GeneratedVectorWidget16.dart';
import 'package:flutterapp/lightsapp/generatedfavoritescreenwidget/generated/GeneratedHychniubnthchWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lightsapp/generatedfavoritescreenwidget/generated/Generated810Widget3.dart';
import 'package:flutterapp/lightsapp/generatedfavoritescreenwidget/generated/GeneratedccmccchnscmuvngWidget.dart';

/* Frame favorite screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFavoritescreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/e283b33ab7375327428a58bc4d7aa0f81936911c.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 360.0,
                  height: 800.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 55.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 273.0,
                height: 450.0,
                child: Generated810Widget3(),
              ),
              Positioned(
                left: 43.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 113.0,
                child: GeneratedHychniubnthchWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.09166666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 33.0;

                  double percentHeight = 0.04125;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 33.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.044444444444444446,
                        translateY: constraints.maxHeight * 0.02375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget16())
                  ]);
                }),
              ),
              Positioned(
                left: 18.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 71.0,
                child: GeneratedGroup4Widget3(),
              ),
              Positioned(
                left: 40.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 24.0,
                child: GeneratedccmccchnscmuvngWidget(),
              )
            ]),
      ),
    ));
  }
}
