import 'package:flutter/material.dart';
import 'package:flutterapp/lightsapp/generatedstartscreenwidget/generated/GeneratedHychmnhiulnvoqutrngWidget.dart';
import 'package:flutterapp/lightsapp/generatedstartscreenwidget/generated/GeneratedKhichmvonhiulnthqutrngsnracvoilightsWidget.dart';
import 'package:flutterapp/lightsapp/generatedstartscreenwidget/generated/GeneratedCngchmvonhiuthqutrngcngphtsngvnhsngcngloanrngratonmnhnh.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lightsapp/generatedstartscreenwidget/generated/Generated34Widget.dart';

/* Frame start screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStartscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            ////overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Image.asset(
                  "assets/images/58b02374af6c7259608d3b397213825017c644cd.png",
                  color: null,
                  fit: BoxFit.cover,
                  width: 360.0,
                  height: 800.0,
                  colorBlendMode: BlendMode.dstATop,
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.6888888888888889;

                  final double height = constraints.maxHeight * 0.0875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.15555555555555556,
                        y: constraints.maxHeight * 0.0725,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedHychmnhiulnvoqutrngWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0333333333333334;

                  final double height = constraints.maxHeight * 0.8275;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.019444444444444445,
                        y: constraints.maxHeight * 0.06125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated34Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8638888888888889;

                  final double height = constraints.maxHeight * 0.055;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06944444444444445,
                        y: constraints.maxHeight * 0.79,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedKhichmvonhiulnthqutrngsnracvoilightsWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8833333333333333;

                  final double height = constraints.maxHeight * 0.08125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.058333333333333334,
                        y: constraints.maxHeight * 0.8675,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedCngchmvonhiuthqutrngcngphtsngvnhsngcngloanrngratonmnhnh(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
